// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCf4VXr--MwHisBts9rZaMJeRshJyK7ZyE',
    appId: '1:756372858984:web:04bff328860ead34aeb3dd',
    messagingSenderId: '756372858984',
    projectId: 'login-lotto-d09fc',
    authDomain: 'login-lotto-d09fc.firebaseapp.com',
    storageBucket: 'login-lotto-d09fc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDozv89h-sOf12NjaAGTKIPlVG8kXyjcW8',
    appId: '1:756372858984:android:91ba6b951f0a1686aeb3dd',
    messagingSenderId: '756372858984',
    projectId: 'login-lotto-d09fc',
    storageBucket: 'login-lotto-d09fc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA88e1Ui0KqicQLtnGH5nckBTRa7-H5tRA',
    appId: '1:756372858984:ios:b8ee9e3e17c16a2aaeb3dd',
    messagingSenderId: '756372858984',
    projectId: 'login-lotto-d09fc',
    storageBucket: 'login-lotto-d09fc.appspot.com',
    iosBundleId: 'com.example.loginApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA88e1Ui0KqicQLtnGH5nckBTRa7-H5tRA',
    appId: '1:756372858984:ios:b8ee9e3e17c16a2aaeb3dd',
    messagingSenderId: '756372858984',
    projectId: 'login-lotto-d09fc',
    storageBucket: 'login-lotto-d09fc.appspot.com',
    iosBundleId: 'com.example.loginApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCf4VXr--MwHisBts9rZaMJeRshJyK7ZyE',
    appId: '1:756372858984:web:50ae26a7d7d42774aeb3dd',
    messagingSenderId: '756372858984',
    projectId: 'login-lotto-d09fc',
    authDomain: 'login-lotto-d09fc.firebaseapp.com',
    storageBucket: 'login-lotto-d09fc.appspot.com',
  );
}
